PREFIX vsd: <http://w3id.org/rsp/vocals-sd#>
PREFIX vocals: <http://w3id.org/rsp/vocals#>

SELECT ?name ?endpoint ?method ?feature
WHERE {

    ?engine vsd:hasService ?service .

    ?service vsd:name ?name ;
             vsd:method ?method ;
             vsd:endpoint ?endpoint .

    OPTIONAL {  ?service vocals:feature ?feature . }
}